import { analyzeConversation } from "@/actions/ai";
import { athleteActivitySchema } from "@/lib/types";

const result = await analyzeConversation({
  activities: athleteActivitySchema.array().parse([
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 106836,
      moving_time: 13282,
      elapsed_time: 13370,
      total_elevation_gain: 635.9,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14278428656,
      start_date: "2025-04-25T00:03:54Z",
      start_date_local: "2025-04-25T05:33:54Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 0,
      kudos_count: 75,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14278428656",
        summary_polyline:
          "{iwnAuzqxMc]fAgKDio@cCsCi@eOgEkYoJgDm@{N{Ac]yJcd@uIgHoCsYyN}m@e\\_SiImyAsi@kEoA_CYyh@RuSmA_FiAc`@iPyDoBgOgJk]yUyGmFuMcJ_f@oQ_RuG_L}Hye@c[iHqEaCaAec@aYqDeE}FcI}DkE]q@w@oDqAmCkDuEgEuH}KeQ_BgBaDsBEWV@rAy@@i@mFmJ_BsBsHoOsFcIut@or@qc@oc@gh@ef@ymAukAoC}CyT}ZuC{CyEsDsFyBkWwEwTiDgD_AoEsBwDwC{BiC{BqDgFuKeDoEqDmDmCmBsa@iV_GcCiCi@AUbB?ZIHWpAsUh@{Fb@}C^m@zCwKnDcHbGgH`GuE|HyDxEyAfFcAru@gJxCQnCBfCX`Dt@fEbCzMxKfExA|D`@fFIxk@iDhGcAzCy@pCeAfE_CpDuCbCmCfRgVtFkJ|AkE|@eEzHwh@|@qCnBoDpCyChEcCbEkAzJsB|IgDvGcEpFgFdEmG|B{EtCmJn@gGZiAjBgDrCyK|A{ErDcH|Wa^dF{J~AwBfOcMbN{MrHkEdMqDly@}Rfj@mMvWkI|qEakB|IkEds@_b@jPoHjPiFvK{B~~B}[pGe@|t@oCjVgB`M[jAa@j@mAIkAs@y@aHqAgBb@i@|A^tJr@lExAhDx@d@~@BvAs@tBiGBaB{@eA}AO{k@`Bwk@bCaG`@_NbBarBdY}OfDiKbDgMrFsMlH{b@vWkHrDqh@`U}Y~LuNpF_cCvbAoQ|FqrBxf@uHnCeGxD}MxMsMnKmA~AkC`F_ClDsX~^yDdIaDrJcBdIcAlC{@jEkC|ImCjGuDrFcEjEaH|EyItDcOdDyAj@oF`DgDxDmBdEcA~DiGpb@eAfFmAzDyC~FkKbOiIrKiEjEqCpBuE`CuBx@yGzAws@hEeFOoFoAmEeCyLwJ_E{AwEk@aHVws@|IkIdBmJxD}G|EuCrCaC|CeFpJ}BjIo@~GeBt[~@`AtCnAr@x@|^nTrG~EdBhB`BfChKpRtCbDtDjCjEpBlD|@fQhCrWrErFjBlGtDxDpEfTdZvCfDdlA~iAxf@vd@`j@~i@xp@bn@nCvDxHfNfDjClDhHzUtb@bK`QxElFx@bDrE`JbB|BnBjB`@~@rc@`Zhb@`Xj\\xTlw@fYpMzIbJfHx[nTbOdJnHrDj^`OtCn@nUpAlg@QbCX`HnBrsAbg@dTvIriAtl@tJrDv`@hHlYdI`QvBz@UfC`@`e@xNlOpDfi@dCvEB~KYrXaAlBk@|Ma@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 8.044,
      max_speed: 12.78,
      average_cadence: 80.9,
      average_temp: 26,
      average_watts: 100.4,
      max_watts: 588,
      weighted_average_watts: 121,
      device_watts: true,
      kilojoules: 1335.2,
      has_heartrate: false,
      heartrate_opt_out: false,
      display_hide_heartrate_option: false,
      elev_high: 932,
      elev_low: 866.9,
      upload_id: 15236964939,
      upload_id_str: "15236964939",
      external_id: "garmin_ping_432360332459",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi ⛰️",
      distance: 101233,
      moving_time: 13621,
      elapsed_time: 13656,
      total_elevation_gain: 1007.4,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14268966262,
      start_date: "2025-04-24T00:30:51Z",
      start_date_local: "2025-04-24T06:00:51Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 8,
      kudos_count: 91,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14268966262",
        summary_polyline:
          "qjwnA_zqxMij@v@cn@aCqQ}E{[eKqTsC{]_Kya@}HoHsC}kAum@qk@}T{`Au]uGaAqi@NcRmA_FoAe^eOyGkDsN}Ios@ig@ux@_Zkt@gf@mLsGob@yXwCcDcFsH{FqGk@kCaBqDwW}a@yB}BuCcBxBiByI_OoHgOiG{Iim@ck@cj@{i@irB_nB}GoHoX{^sEyDuGsCam@_KuI{CyDmCkDsDmLkTwGcHmc@aXqM}D}@@_EzBg_B`bAqd@fXi{@~Rib@zMunC~i@s}Bj`@R~AjDfId@jCjBpp@QxDaDlY}DtTeHvh@wTpm@w@nAkAQcJkE_E{@g@m@eAwEuDTa@[c@wFNeE_BiGZgHo@sMLiC]iLSgDwAqJyFiLIqG}@wCn@oE@gJ_AuCSuC_BuHwAoCWqBwA{Dg@_J{@{FaAg@y@f@[rEmAbByARUX]fK{EhD{@xAuBn@uBtGcBxAO`AE~CyBrC_@Ct@}AJaEmBpAeAi@sBCaA[iBeCVOtDf@`Da@eIgCyBUlE[bCs@hCG@W}Bg@wDN`EuBlBBHQeBWuDX}Ce@tC_@qBs@TTvABHToCZBTxCTjD]dBZET_BIsEpBTTtCc@~Bd@RPOR}BCqBr@iF\\tBTdI~BA^qCPcEo@YRlCtCdCD|Aj@f@Qh@y@V?KjEs@lAVJ`C}CHsEbBwAtB}GxBm@bAeBnAi@fCwBV}JVa@bBQbAuABiCZeBp@Y~@^dAlFh@fJvA|DPrBxApCtAhG^vD~@vCBjHy@vG`AjC?jGtC~GlBxCtAzJJlHf@dGI|Dh@vJ?vDWrD|A`GMbEZvFd@\\tDQz@xDn@fAzDz@`JhExATdVgp@xG{f@xDwT|D}\\SgQmAea@k@iDiEiKRg@h|B_`@pvBwb@rYcG`e@wNlu@{PzHwDr|BcvAxF_DdCR`EnAjHpDx_@zUxGlHtLjTxC|CtDhCzIzCtj@dJ|EbBdGlDv^~e@fxBzsBxe@xe@zq@ho@lCvDbHjMrBxAdDbFlOrYfQnZzGxIpAfE`HnM|AhBrfBzjAbx@vYlt@bh@~MdIdR|IjTxIfFfApP~@zh@O|CTpD|@lbB|m@`MpF`gA`k@hJlDld@rItTnGpRhC|@UrCf@ta@nMrRxE~m@bCxt@aChd@e@~JL_@\\}@FmPG{\\h@sHZSS|@e@tHUj\\c@vRPuB`@oNEiMf@_Z@?k@^KzM_@Je@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.432,
      max_speed: 15.36,
      average_cadence: 77,
      average_temp: 26,
      average_watts: 100.9,
      max_watts: 490,
      weighted_average_watts: 147,
      device_watts: true,
      kilojoules: 1373.1,
      has_heartrate: true,
      average_heartrate: 140.4,
      max_heartrate: 200,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 1369.8,
      elev_low: 884.2,
      upload_id: 15227085180,
      upload_id_str: "15227085180",
      external_id: "garmin_ping_432056745416",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 101986,
      moving_time: 12915,
      elapsed_time: 13012,
      total_elevation_gain: 613.4,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14248331238,
      start_date: "2025-04-22T00:31:16Z",
      start_date_local: "2025-04-22T06:01:16Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 3,
      kudos_count: 111,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14248331238",
        summary_polyline:
          "giwnAqyqxM_DUeC?_Yz@yG@mo@kCuCm@cMqD{N}EmK_DkDo@_K{@cDm@_EcA_CcAwOoEsFkAqX}EkD{@uCcAiD}AgkAgm@mMoF_RaHc}@k\\oLaE{Cw@kCQcb@XyEGiRkAuB]mC}@w]aOmHyDoLmHeTgOyH_FeG}EkHgFeEiCsc@kPeO_F_CeAmVoPc_@gVaEeC}B}@aJkG_CqAqScNmCcCwEmG]YG_@i@y@eC_C_BuB]qBm@mBk@gAw@wAoB}BiH{L{DyFqCyEmA_Bu@o@wCaBDWd@K`Ai@JSAKoFuJqBuCiAmC}EkJcGuIaHmGmQqPsWyV_RgRwQkQ}]s\\sG}Fa^q]kp@wn@uCeDuTuZgBqB{CiCsA_AiB}@_DgAeBc@aImAsL{B{PeCyDcAiDyAgEuC{CeDkBwCoHsNiCiDaD{CwDiC}]}SgEuAuBe@gE}Ae_BwRuy@{IcRaDaDUai@GkYTeg@MqIFigAMsCF}eCKsZc@ke@HuiAi@sb@a@uCRoLQiDUoDm@yEiBeDcC{BgC{BoDi@iBcFmI_^wk@eDgEeF_EcGqCyEqA}Gs@qR_AuIU}Kw@yiBkJuDIsELcFj@wEbAgZjJ__Bxd@gDj@}CPqCEeBMgDo@ih@yN}By@gBmA_K{CwAYhDnAzy@jUbEn@jEN~Da@xCo@t_Bce@pWgIpD}@jFs@rEShFFpfAzFje@zB`In@vFNb[dBnCb@jFrAfFdCdEdDbDvDxg@dz@vBhDlB~B|ApAfAR~C~AbCl@jC^hDH`E\\bf@h@`pAp@|h@G`\\^peC@psADrh@L~TUfj@HzE\\hQzCzk@dG`kAdNx\\dEj@TjCVdDn@lDpAxGjDh[jRxCxBtCzChB~BvA`CzH|NhDvD`ErCxD~AvDbA~RtClFfA~NbC|Bp@dBv@jCzArAlAz@^fY~_@xChDfg@~e@|AjB|BhBp\\z[bMdL~\\t[lQbQ|RjStSvRj]r[vBvCbIxNpCrB~BxDpBlE~JvQbTd_@`EtEh@v@Z~Ap@bBpFhKzAtBrApAnBtAb_Alm@t`@|WtClAtIpCr`@tN|GnCfL~HbInGvHzExRhNzN|IrHvDp]vNlBl@tARhPbAlJLf`@WzBTfDz@xJbDxvAzh@pMzFngAlk@xD|AtDfAd_@xGxJhCnGtBfE`AtQdCrAKpC^fNdElRnGnJbChGpA~b@dBvHPx^eAbIMfAWjHWnQIdEObAFzU@NLSPm@D{OEoDHmDX_M@uDMaDHeDXQW@e@VK`DS|HILIBc@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.897,
      max_speed: 13.82,
      average_cadence: 78.4,
      average_temp: 26,
      average_watts: 89.9,
      max_watts: 700,
      weighted_average_watts: 129,
      device_watts: true,
      kilojoules: 1159.8,
      has_heartrate: true,
      average_heartrate: 126.9,
      max_heartrate: 197,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.3,
      elev_low: 884.2,
      upload_id: 15205567557,
      upload_id_str: "15205567557",
      external_id: "garmin_ping_431413412557",
      from_accepted_tag: false,
      pr_count: 2,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Another day, another crash 🤕",
      distance: 116445,
      moving_time: 13528,
      elapsed_time: 15180,
      total_elevation_gain: 771.8,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14228793602,
      start_date: "2025-04-20T00:34:39Z",
      start_date_local: "2025-04-20T06:04:39Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 9,
      kudos_count: 117,
      comment_count: 21,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14228793602",
        summary_polyline:
          "qewnAw}qxMwZxAiU`@eR@uXiAmHaB{d@_OmEy@cMkAe\\qJke@cJ_HiCqfAwj@{I}Deu@iY_p@wU{DcAwCWui@PkQiAkFqAo]yNmIiEuLoHa^mVsViQsw@oYsIkGml@{_@gMaHe]eU}BmBgHuJqGmHa@yB_C{EoWua@aBgBaDmBnBkAJ]sFwJyAkByH{OyFkIyOeOaA]qCArBDJM{eAoeA_g@_e@snAolA}CmDaXm^}DgDsHeDmX_FcSuCaEkAoDcBuDkCkD_EmI_PqCeEO@[dB[Ad@gCuCsCgb@kWcBuA}GyBsFgAcTkCcoAaOou@eI_OkCcE[cj@EcXTw_GUyj@k@oZNenBmA}SCiD]cEqAoDkBmDkDaD_Fu@{Bed@yt@oEsFuDwCeDiBcE{AcE{@sd@{BcvBcLwJC{Ed@qE~@cZfJ}`Bpe@oEn@gFDqGy@_~Acc@otByl@_F`Ny@rJbC|@nAzC?rB\\bEOfHv@vHGhBu@zA@`@vCdFfB~FDxBhDvCPd@a@~BeDXgBjBi@xA}@jG`AlBNbCZpMbC~AlD~@~AzAPr@q@\\kL@oAdAeBfFFlBjAjA~@nEw@dGBjKu@lQh@lGvA`GnAvB`@hBq@tB_Gd@uAtAeC~EiEpAeBc@hGg@nFwHxA]hDCv@eBKoAsBqEeBgJMqDv@sOAeKx@kG_A{EgAeAMcBhAiE`BoBlL@n@MNYI_@cB}AoDeAiBcAk@oA[}FFeEe@sC_@}@l@{Ed@yBzAiBxDc@f@oCwDgDKoCs@}Ak@iC_D{Fn@oBHs@AiBs@iGN{Ie@cHcAyBsBe@OYt@qJjFiO`fBjg@`lBnh@xH`AnEGjEs@b_Byd@zYeJlEcAzFo@pHK`SfAdNTzm@zDre@jCfc@lBdFx@vEvAjExBfEdDfEhFjk@b_ArDrDnG`ChFz@~Kf@he@f@|qAt@xg@IlY^pyG?vj@FpF^xPvCnlAtMncAzLpMnBvDnAxGfDh`@bVbCzBjDjEhKvRzCdDjExCtD`BlD|@dj@~IlFlBzFbDfZ|`@jC|Chk@jj@`kAvgAvf@vf@~q@lo@jCrDdHlM`C~AlChE~N~XfRf\\zBnDbDhDh@xBzB|EfF~I`ElDxaB~fAxv@|X`DjBxStOvd@|ZxMjHf`@hP|Dp@~SjAfg@WvDf@tCz@|xAfi@nOpGbhAnk@vG`DxFhBtc@jIzTlGjRhCj@Y~B^`h@|OvN~Cvj@zBva@eAxGc@Te@n@{E",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.07, 77.6],
      average_speed: 8.608,
      max_speed: 14.38,
      average_cadence: 83.9,
      average_temp: 28,
      average_watts: 119.1,
      max_watts: 738,
      weighted_average_watts: 149,
      device_watts: true,
      kilojoules: 1611.1,
      has_heartrate: true,
      average_heartrate: 152,
      max_heartrate: 196,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 995.7,
      elev_low: 884.2,
      upload_id: 15185090243,
      upload_id_str: "15185090243",
      external_id: "garmin_ping_430802346796",
      from_accepted_tag: false,
      pr_count: 6,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Coasting 🥱",
      distance: 106731,
      moving_time: 14655,
      elapsed_time: 14791,
      total_elevation_gain: 637,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14209400183,
      start_date: "2025-04-18T00:24:39Z",
      start_date_local: "2025-04-18T05:54:39Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 1,
      kudos_count: 102,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14209400183",
        summary_polyline:
          "mhwnA_|qxMgTtAmRZqGGwk@gCaO_Ee_@mLoQmBqNgEmOeE{`@oHiHkCsgAik@qGwC_QaHwtAkg@_EkAsC_@yi@P{QgA{FqAs^oOqH{DgM{HqS}NsHyEcJgHaK}Gch@oRkJyCqD_Bwm@oa@}MqI{By@g]aUuGiFoEcG[MgAqBiFaGi@aC{AmDeXub@kBsB{CiB@QlB{@D_@oFsJmBoCaHqNuFgIaw@ut@g_@k_@ek@ai@kmAgkA}CsD_SoXsEaFmDmCeGcCkYeFqQkC}DeAeDyAaDwBgDgDcBaCyIyPoCkDuCkCoc@eXwEwB{FcBDShBB^g@xAaXj@}EZgBZk@bAkExAqEvDkHjGkHrFgEfHmDjGkBrDs@tv@qJlCQnCDjCXnCr@jDfBnO~LlDlA`Ff@tc@wBpNcAjF{@tEsA~CwApDyBxFqFhMePlGwIpC_FrA{DdAwErHgh@|@{CxAoChDyDvEsCpQaEfJqD|FuDrEkEfFyHtCsGhBeGl@qEhCuHhEwOhBsEfBcD~Xm_@fEkIfCoDfMcKlNeNrCqBnDiBvFmBvjBoc@nXoIxsEelBhHmDvt@ac@lOwGfNmEnQiD`yBsZlKu@nm@yBdTmA|Dc@nNc@hAc@^w@@sAu@cAcHqA}A\\s@xAVpIx@rFl@nBl@dAx@d@bAAr@Yf@s@nBwFA{A[m@c@WgBGec@hAyu@|CqS|BelBxWoHhAkNzCuN~EmJnEep@n`@uJtEcUjJwSjJqhDvuAqPnFqqBtf@iFxA{CnAcGtD}L|LsOlM_IrMmXt^wCxFcB~EwCrK{AbKgA`BkCpI}A|DaCjEeB`CqFvFuFvDmIrDcQbE{EdCiEbE{BhEyAbF}Gle@cCtIkDtGwLrPwHzJeExDgDvBaElB{C`AuE~@gs@bEoFOmFsAoDoBeJ{HaC{AkEyA{D_@{ELwk@dHuJnAcH|AqIlDyHnFgCjCuCxDuEzIwBvHAxAm@zEaBj[N^f@\\tf@xYnFdEzA`BbBjCfKlRbDnD~DpCpElB|D~@nP`ChXzEzEfBhGvDvClDlThZjD~DvmApkAlj@fh@`e@je@xq@`o@hCxD|G~LpCtB|BrDfB~DlU~a@dJtOfFdGl@jC`CpEhEvG~BbCHh@dd@rZnTbNzi@l^h`@bNrUzItM|IfHxFnIlFvQpM~NbJtGfDp_@zOpDx@dRfAxJHt]YpBLnCn@|HdCpdA|_@`^nN~jAhm@nEnB|DlAdd@lIjSbGjSrClAOtCd@x`@dMxR`F`b@hB~M\\jAo@hAKha@oA^q@DyAj@{C",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.07, 77.6],
      average_speed: 7.283,
      max_speed: 12.3,
      average_cadence: 74,
      average_temp: 26,
      average_watts: 76.9,
      max_watts: 392,
      weighted_average_watts: 96,
      device_watts: true,
      kilojoules: 1126.7,
      has_heartrate: true,
      average_heartrate: 107.6,
      max_heartrate: 149,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 932,
      elev_low: 866.8,
      upload_id: 15164763271,
      upload_id_str: "15164763271",
      external_id: "garmin_ping_430174826771",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi ⛰️",
      distance: 101356,
      moving_time: 13708,
      elapsed_time: 13861,
      total_elevation_gain: 1007.8,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14200029614,
      start_date: "2025-04-17T00:32:08Z",
      start_date_local: "2025-04-17T06:02:08Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 1,
      kudos_count: 112,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14200029614",
        summary_polyline:
          "yfwnAu|qxMmSdBoUf@gr@cCgSqFsZsJ{R_Ca]{Job@aIoJkDkmAqn@y{@u\\on@wTcGiAma@^aIKwOcAsFoAy_@aPiH{Dei@_^{WmRmw@iY_PaLqf@k[kf@kZiHqFyDwE_DcFyEeFuAsFcYyc@mB{BiDsB@UbBi@Ti@gJkOyGmNkGiJun@el@em@{l@}pB{lBmDuD_Vg\\oCsCuEqD}GiCgX}EcPyBgKiDyDgCaDcDiCaEmGkM}CyDyDoDac@yWqLqDmB@aeB`fA}c@zWy{@dSe_@tL_E~@ojCxh@s~Br`@Br@~E`NnB`q@IvCuDn\\uEtWaGdd@uTjm@y@vAaAOgJmEoEgAe@s@{@eEyDPg@i@[qFLkE}AyFXsIo@}LLwBa@_GMoIuAmJ_GqLGkG_AyCn@sDBcKy@wBUkD{AcH_BiDQiB{A_Ec@iI}@kGiAs@u@f@[tEiA~AmBr@e@fK{BrB}At@{@zAoBd@{@fBq@`DoBlBSzEyBrC[A|@eCCwCaAdAu@Ru@o@oDUwBiCXYvDj@nCMNSyHcCcCUlE_@bCs@hCGDUcCk@qDRdEwBfBBFSgBUmDXqCQMUrC]{AYY]XX~ARmC^CXdDPhDYbBXSVuAKsExBXLtCc@|Bb@RPKPyCF{Al@eFb@|BPfI`CI^wCJeEk@UTtBhCbBXdAGbAr@z@[z@y@G`Eu@xAVFdCeDI{BNoAfBcBnBqGf@]jAGdAeBrEcDd@kKfBk@lA{AZiFp@g@jA`@`AxFh@pJtAhDT~BvAjCtAtG`@hE~@hC@vIy@`F|@fCDpGpClGjBtCzAfKRnCCpDb@tFOjDn@tKYzIzA`GKvDVdGr@^jDQ~@lE`@l@~D`AxI~DbB\\dVmo@fH{h@pDmSzDs\\DeCiBmp@k@uCaEuJRs@fe@uI~vAuUboCij@vb@{Mpz@yRhQ}JdsByoA`FiCzBNpJpDrc@bXvErEvNfW~CdDjD~B`JbDvj@bJzGlCvFnDx\\`d@faCv|Bx\\`]zq@do@pCtD~HtNpCrBvZzj@fMdT~DhEb@~BxCzFvG|I`@bAbdBxhA~w@tYhWbR~k@x_@de@rSlGbBrN|@fLPb`@U~HzAr`B`m@tMzFpgAjk@nJlDn`@fHbXrHxRrCvAOxBZjb@zMtRrE`l@vBpi@kB|Q[tSYfUVmB^gQIiF\\o^TN]`BQ`e@s@pQDNP_THkYd@uJZe@@IWRk@`NYNi@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.394,
      max_speed: 14.26,
      average_cadence: 79.7,
      average_temp: 25,
      average_watts: 100.4,
      max_watts: 600,
      weighted_average_watts: 139,
      device_watts: true,
      kilojoules: 1369.9,
      has_heartrate: true,
      average_heartrate: 129.2,
      max_heartrate: 187,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 1368.5,
      elev_low: 884.2,
      upload_id: 15154977078,
      upload_id_str: "15154977078",
      external_id: "garmin_ping_429858929257",
      from_accepted_tag: false,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 102012,
      moving_time: 12788,
      elapsed_time: 13036,
      total_elevation_gain: 606.6,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14180716757,
      start_date: "2025-04-15T00:38:39Z",
      start_date_local: "2025-04-15T06:08:39Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 1,
      kudos_count: 113,
      comment_count: 2,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14180716757",
        summary_polyline:
          "wgwnAk{qxMeDHaL@gELcLt@{GFci@wBmCEgHaBkYaJgK}C{Dq@}LkAqG}A{Au@aTaGkYeFkFiAyC_A_EcBq[cPij@uYuHiDeOeG}uA{g@mEiAuCUm`@XyHKaQkA{AWqC{@q^mOmGcDiNwImR_N}GiEeSeO}CiBe^}MmS_HaDsAqHiFog@m\\gKsGqCmAw\\uToCoB_DsCyE{GgGeHc@q@[iBeAeCsFoIiFcJmCwDoEqHuB_CaDiBFMjB_AHYEKmFmJoBsCeHwNaCwD_CyCcBiBwD_DsEuEu`@a_@uImIs\\s\\eTmSiSaRknAglAkDgEkS}XkDsDeE}C_DsAmCy@yUeE{S}CyDgAkD_BsDiCyCcDcC}DoEaJiB_DsBcCaEsDcb@}VkDmAsCo@oEaBo~AoR{Ea@kCc@kl@kGwHeA{JkBaEUy]I{c@Vif@KcNF_bAMwhCCa\\c@of@HasAo@uZ[eCRePYsDi@wEcB{BoAgDcDcDaF[mAs@oAae@_v@eDyDiCuBcDmBgDsAyEmAsFo@eS_AkK[cLy@c{AwH_KaAqEK_FJ{D`@gDn@c]lK}{Arc@qCt@uBV_A~@oAPqBEuAQ{Ce@cDy@_F{AeCgAe^gKuA_A_A_@yJwC]IMFvDlAzy@lUpDj@rDJbCGxFeAheAuZv_@aLfRaGrFkArEa@`EK|DJnfA~Fnb@lB~Jr@`JThQz@|Fd@nGtAjGnCjE`DdChCtAhBzg@hz@|CrEnCjCdAL`@ZzClAdEz@`Nr@pd@d@ppAp@jf@InX`@nODj{BAlbAJpv@DfZUhg@JjFb@lI~AhFv@lf@dFff@vFtx@vJhMfB|BPtDt@vC`AdDxArBhAbZlQ`FhDzDvDv@bB`BrBzEpJpCpEdCjC|DnC`EfBtD~@dSxC~FjAtJxA|Cr@nEfBpBjAlAdAx@\\tBfCpUt[lD`EhlAdjAnKrJlN`NpOpN|QrQ~PjQlWnVtU~StCxCfDbFbGbL|Av@dApAnR~]tSh^fFhGr@rCxE|IxBxCxAtAVr@|[jT`z@ti@lLdIpBz@`IbCjSnHjRbH~BdAnIzFzLhJfGxDzTvObMxHbGzCr^jOzAh@hB^hRlArLFx\\WpCXbD~@tL`EntAxg@lMxFhgAfk@hDvAjEpAn_@|GrIzBfIlChCh@jRjC`@@n@SrCd@`Y`JzH~BdGdBzEz@xAd@hd@fB`KNt@Mhb@}@tFc@rFMb_@e@tNJR@FPUNm@FoOGiMd@kI@oCOuKFD]`@KdDQnHMLG@a@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.977,
      max_speed: 13.56,
      average_cadence: 79.3,
      average_temp: 26,
      average_watts: 93.6,
      max_watts: 386,
      weighted_average_watts: 113,
      device_watts: true,
      kilojoules: 1192.8,
      has_heartrate: false,
      heartrate_opt_out: false,
      display_hide_heartrate_option: false,
      elev_high: 933.3,
      elev_low: 884.2,
      upload_id: 15134880781,
      upload_id_str: "15134880781",
      external_id: "garmin_ping_429215297255",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "📌 5K ✔️ - 2025",
      distance: 131383,
      moving_time: 15483,
      elapsed_time: 16887,
      total_elevation_gain: 828.2,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14161372531,
      start_date: "2025-04-13T00:38:19Z",
      start_date_local: "2025-04-13T06:08:19Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 5,
      kudos_count: 111,
      comment_count: 5,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14161372531",
        summary_polyline:
          "wewnAi}qxMeIh@yb@z@sp@iAoUmGgWkIaTeCi]eKub@cImI_DgfAoj@{K_F{v@eZkm@cTgD}@sCOgi@PoPcA}FqAse@uSeOgJ_^iVgVeQcy@oZsu@_g@mFgDsA]cPkKqQsLeE_EwCyEoAcAm@mAgDuDmAiEeBcDgWoa@cCeCoC{AhB}@Ri@yIaOiH_OiEsG{v@wt@i{CcwCsYi`@iDeDyDoCaG{Bak@iJuJiDsDiCiDuDqKaS}GwHsc@mXcFcC{F{AdCe@`C_^d@cDbEwMbEsHpFmGxFiEjI_EzLuCzt@cJtIKrFdA`ErB~NtL~DrA`E`@jEChm@uDhJiBfKyEjH}GdSmWnEqHxCgKvHwh@~@{CfBeD`EmEjDmBzRwEjHsCpGcEfEyDpF}HxC{G`BcG~A{JfBkDrEePnEgJpXs^tHcN~NyLfMgM|IkFvKaD|eB}a@rZsJzoEajB`HeDpw@yd@~LmFnO}EfNqCh~Bw[ptAyGpL]nAe@b@_A@}@_AuAyGkAeB^m@tA`@vKf@|C~AfEv@b@`ABvAeA|BeG@yAy@aAsAQia@fAet@rCgOnAsuBxYcYvFgKrDuK`Fyn@n_@mMlGkp@~Xi_D`qA{S|GmqAd[_h@dNuInFsLrLoOdMgH|LsX|^qFrLsDnMwAjIuDjLqC~G{DjG{EfF{GzE_IjDkSfFgEbCcDhDuB|DwAtEqHjg@yCpJ{ClFsS`YqI~HeIbEeIlBgo@vDcGJeDYuFeB}O{LoCuAuEeAuEKs_ApL_N`FyE~CyDjDwEfG{DxH{B~Hk@rD{JteBuK|_AwA~R@rQx@zK~CjPtOfi@|@xKYpKySlgB}A|WcAvI{s@`jDkFrc@s@\\[i@bEg[`@w@zb@esBtQ_~@dDab@hPwuAfB}QJkJq@aIqNah@{BqJaBkMo@gMHsJj@_JbNapA~Dqy@Qu@cBm@Pc@hEz@jGlC`d@lXhEbE~C~EvJnQ~B`CvDfCpJdDdk@jJrEdBbHxEt\\xc@jg@bf@nBfCjDlCfeAlbAl`@n`@ly@vv@dCjDnHxMfCjB~BzDbO~XvSp^jFhGr@rCbJrPvBtBhe@tZnq@nc@pBd@bH~Ep^lMZAH_@P|@t@\\vSvHzPfLlGfFxd@xZlLnGxQ|HpApAlJ|DbFz@hThAbg@SpLpCbwAvh@hN~FllA`n@`JfDl]jGvZjIzRrCdBMdDl@l^hLvTrFjk@zB|h@mAbAa@xLUr^e@dNVTQFTmC^aOAsGb@a^R]]D_B|@iF",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.07, 77.6],
      average_speed: 8.486,
      max_speed: 15,
      average_cadence: 86,
      average_temp: 27,
      average_watts: 112.4,
      max_watts: 703,
      weighted_average_watts: 136,
      device_watts: true,
      kilojoules: 1735.1,
      has_heartrate: true,
      average_heartrate: 141.3,
      max_heartrate: 188,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 937,
      elev_low: 866.8,
      upload_id: 15114660188,
      upload_id_str: "15114660188",
      external_id: "garmin_ping_428582196010",
      from_accepted_tag: false,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 102002,
      moving_time: 12876,
      elapsed_time: 12927,
      total_elevation_gain: 613.9,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14142585340,
      start_date: "2025-04-11T00:40:02Z",
      start_date_local: "2025-04-11T06:10:02Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 1,
      kudos_count: 109,
      comment_count: 3,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14142585340",
        summary_polyline:
          "qiwnAwzqxMaGDkPp@gPH_Qe@}^}AiTaGeQaGcEkAgGcA}KgAiG}AcAi@qRsFu]oGuEgAiDkA{CuAmgAik@}FgCsJ{Dsf@}Qym@_UqEyA}Cy@oCUo^XyHEgSmAaCc@_Bi@m]yNoHuDaOeJ{QuMuH{EiNmKcHsEac@cPsOeF}BaAmKoHwh@e]oG_Ec@We@EeAm@mSgNwBkAgA_A{H{EqCaDsE_H_D}C_B}BSoA[gAyAwCiDcFsFmJcFsHsC{E}BcCsC{AAOpBcAFWEIiFoJmBqCmBiE{DuH{CwEiB_CcNoMiTaSeSsRo^q^i^a]sIwHkoAemAkDgE}SyYkBqBaCqBqBqAeCiAkCy@}WwEwRsCyEyAkCqA}CwBqCsCkBqC{EkJc@mAaBiCuCgDmBeBuDiCa^aTcFcByAYcAk@oD_AmIgAazAkQ}s@yHuPwCeE[}i@EmSTaj@KgrAG_gCAs^e@eg@H{lBkAcDRyNYcEi@{DkAaCoAcEyDeDaFi@gBuIuN_Z{e@yB}C}B}BkFqDwF}BkGoAiHg@mNo@_KYeL{@kb@oB__AcF{J[uFNqCXgFfAuZlJi~Ard@gDp@{DXkEIwDk@qb@uLwAm@iGaB_@c@sBy@{KcDMBdDhAjz@rUpDj@|DLnDSlE}@j`Bke@fWaIdEcAxEk@`FOtDDflAnG`]|AtLx@lJVlQz@dHv@pEhAlFbCxEjD~BdCxB`D|e@nw@tDtFnChCfAPjElBvEx@bEJhF^fe@d@rkAn@bYIzTDjV\\bfC@rh@Lxn@Czb@HvYUzh@HnFb@nJfBzFz@jf@bFnd@hF|K|AxKfA|g@lG`G`AhFr@dEtA`FdCv]|SlCrBlDlDhBnCjGzLpCjExC~CxDfClDxA`EdAvQlCnGnAtN~BnBj@xB`ArGbEtCjDrR`XpEnFth@jg@hApA~b@|a@lIpH``@v^dOzNxLhMdPvOrf@hd@nCtDrHzM\\`@|AdAf@j@zBvDdBrDvSp_@~KlRt@dAbDbDPfAVz@rAtCfDzFxArB~AdBb@`AdhA`t@lZjSvCpApH~BrQpG`T|HxBbArKlH`JdHhIfF~RnNjQnKpEvB`V`K`G|BlCp@nUpAfIBh]UvBRbCl@nH~BtsAdg@dPzGhjA`m@dGbClGzAh[tFlCl@xOzEdDt@|QjCbAS`CZnFxA`[bK`ItBbEp@v@\\n[|ArQh@rc@kAhE[rIYb\\_@jSAXDLNIPmBJkKGuFDaHZaPFyAGwFXGMBe@ZS~M_@JMDq@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.922,
      max_speed: 13.68,
      average_cadence: 82.2,
      average_temp: 26,
      average_watts: 100.6,
      max_watts: 434,
      weighted_average_watts: 121,
      device_watts: true,
      kilojoules: 1296.7,
      has_heartrate: true,
      average_heartrate: 130.9,
      max_heartrate: 173,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.3,
      elev_low: 884.2,
      upload_id: 15094926053,
      upload_id_str: "15094926053",
      external_id: "garmin_ping_427941281269",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi 🤕",
      distance: 101320,
      moving_time: 13159,
      elapsed_time: 13726,
      total_elevation_gain: 1001.1,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14133149974,
      start_date: "2025-04-10T00:34:46Z",
      start_date_local: "2025-04-10T06:04:46Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 15,
      kudos_count: 109,
      comment_count: 12,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14133149974",
        summary_polyline:
          "}iwnAmzqxMah@dAyp@cCkVyGeWgIeS_Ci\\sJif@oJ{HcD}jAam@abAs_@ch@_ReD}@yCWka@ZuHKoPiAgFqAc^gOmHwDsKwGm^sVeXsR{v@yXev@og@iF_DmBs@y\\sToI_HyNcRsB}GkXub@_CkCwCaBjBiAHi@yIyNgH_OuFaIqz@ex@evC_rC}Xs_@cEeEeEwCqG{Bgi@uI}JeDuDcC_DcDsB}CeIyOcImIcb@}ViNiEs@BsBhA{fCx|A{z@zRia@nMyNzCcbCdf@a|Bz_@Al@fE~J`@dCjBxp@QpDuDv[cDrQgH`i@{T~m@{@pAgLaFcE}@e@k@kAsEoDPg@]_@wFLaE}AgGX_Jm@kLL}Ba@iGSoIyAuJwF{KEkGu@aBKeAv@uE?qIeAaDMeCaByHuAoC]aCqAmDg@}IeAiG{@_@u@\\[dBAvBkAdB{ANU^_@fKuE`D_A|AyBt@u@zAm@xCsBvBMtE_CxC_@Cp@oAPmEiAfAm@Hy@k@sAF_B[sBiC`@WdDh@`DMFS_IeCeCWbF]dG{@@QeCk@yDTpEaClBCmB[sC^kDWKQrC_@uAY][|Bl@sCZAThDVdD[dB\\KRiBEgElBNPxCe@rCl@C^qCBeBn@iFb@zBL~Cx@dDhACZqCPiEk@SX|AjBbAf@vBBpAf@zAsAPHO~Du@xAb@D|BaDBiE|AuAxB_H^[tAI~@cBzEgD`@gKX_@vASbAuAJeD^sA~@U~@x@p@~Ef@jJvAfDVjC|AnC|ArHXnDv@pB@lJy@pEdAzCAxFlCnGrBbDxA`KRbDGnCd@rFM|Dl@xK]dITbBfAxCIxEZtFj@^rDOz@~Dn@~@nEbAxK|Eb@m@nUgo@bHoh@jDsR`Eu]eBes@e@qCqEwKNg@||Be`@|nCej@tb@{Mv{@eSneCy{AvEeC`D`@rKjEv`@dVlFfFpN|V~ChDhD`ChJfD|k@pJdFnBhG|Dl]xd@`xBvsBnd@vd@xr@~o@dDtEzG|LpD`Dte@f{@tGhIt@vC~FfLjC|DzeBxiAlx@zYbv@fi@zOlJ`ZrM`NvEvVvAhf@SxCZrD`A`zAzi@dNzF~sA`r@jGbBj`@dHjThG`StCrAQnDr@n_@tL`RxEvl@dC|o@kB|Wi@d\\@vARmSHs[ZuI`@QSbHq@za@g@xNFHRcAXkZTiQAsJ`@a@c@F]bBOnKSXq@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.7,
      max_speed: 15.7,
      average_cadence: 83.2,
      average_temp: 25,
      average_watts: 114.8,
      max_watts: 459,
      weighted_average_watts: 152,
      device_watts: true,
      kilojoules: 1505.5,
      has_heartrate: true,
      average_heartrate: 142.9,
      max_heartrate: 199,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 1368.2,
      elev_low: 884.2,
      upload_id: 15085083900,
      upload_id_str: "15085083900",
      external_id: "garmin_ping_427627482264",
      from_accepted_tag: false,
      pr_count: 6,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi ⛰️",
      distance: 101320,
      moving_time: 13783,
      elapsed_time: 13850,
      total_elevation_gain: 998,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14112780379,
      start_date: "2025-04-08T00:37:32Z",
      start_date_local: "2025-04-08T06:07:32Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 3,
      kudos_count: 105,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14112780379",
        summary_polyline:
          "ejwnAqzqxMij@bAqn@aCoReF{YoJwSiCy\\sJwd@{IcI}CokAqm@_ScIixA}h@cHoA{i@PwRqA}DaAof@gTaOcJst@ah@_x@sY_u@sf@gGwDgCcAsc@yYgR}Ua@}B}AaDgX_c@_BiBkDoBjBgAL_@_JmO}GkNqFcIuvAotAqzBivBeYy_@iDmDgEyCwG_Cyi@{IiJ}CaEmCmDwDeLaTcGsGqd@}X_N_Es@D_E~Be_B~aAgd@`Xm{@bSaf@`O}jCvh@o}Bf`@Mf@bExJj@jCjBhp@MvDwDl\\gDrQcHzh@gUvn@q@|@mL_FeE{@g@q@{@qE{DTc@]Fm@c@aEJ}E}A}FX}Io@cLLaCo@gQ_BkKsFcLIgG_AyCp@sDDsJgAkDMgC{AmHcBiDQiBwAsDe@wIaAeG{@e@w@\\[zACzBeA|A}AZY\\]~JcFvD{@xAkBf@w@`B{@pDgBbBQvE{BrC[Ed@u@XkBCyBgBrAmAm@wBA}@[iBaC\\ShDh@dDODQ{HeCkCUfFa@tCu@pBCCUgCg@wC^YMfE{BhBLH[gBUwC\\oDOK_@rC_@uBm@~Bl@eDh@tD`@fD[hB^qBDuE~BTJnCi@nCb@RNITsCF_Bj@kFZLRdBDjIfCSVkCNoDk@a@PrBjCjDR`Ah@pBuAFpBShBs@fAZH`C_DDmEpBsBnBkGjBc@~@_BvE_Dd@iKV_@|A]bAqAZiFn@i@hA^dAhGb@tI|A`EHdBfBfDpArGZnD`AtC?rIu@fFHr@z@dBAxFtC|GfBlCxAnKTzCZlLIxCh@dKWjJzAvFKjEXpFd@b@rDQX\\n@nDh@r@|Dx@vJxE~@DjVop@bHuh@pDqStDc\\DmBiBep@c@oCaEwJAcAn}Bo`@h_Cme@`PgDjc@cN|x@gR~cCuzAdGeDzBF~E~AxFpCpa@dWtGjHtKhSzCdDxDlCbJ`Ddl@rJfDlAbHfE`^je@ryBjuBt`@x`@ru@|r@vChE|G|L|CdCp\\rm@zI`OjFpGPrAbA`ChFzIpD~EdeBviA`x@tYzVzQbj@n^`G~Cr_@`PdEfAdPjAlML`^UxCXzDdAldB`o@bLfFteAhj@bJdDr\\`Gt[rI|RrCfASzCh@rb@zMhQjEfg@pBzFBdf@uApMw@zYSnS@NR}@`@_NKc]Z}Kh@IWf@YjCOn\\e@xV@f@^sSGo]h@qFd@q@SMe@nEi@zHKNk@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.351,
      max_speed: 16.02,
      average_cadence: 80.6,
      average_temp: 25,
      average_watts: 101.3,
      max_watts: 515,
      weighted_average_watts: 146,
      device_watts: true,
      kilojoules: 1385.3,
      has_heartrate: false,
      heartrate_opt_out: false,
      display_hide_heartrate_option: false,
      elev_high: 1368.5,
      elev_low: 884.2,
      upload_id: 15063886653,
      upload_id_str: "15063886653",
      external_id: "garmin_ping_426991232814",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 108690,
      moving_time: 11408,
      elapsed_time: 11408,
      total_elevation_gain: 653.2,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14092906679,
      start_date: "2025-04-06T00:35:41Z",
      start_date_local: "2025-04-06T06:05:41Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 19,
      kudos_count: 130,
      comment_count: 4,
      athlete_count: 2,
      photo_count: 0,
      map: {
        id: "a14092906679",
        summary_polyline:
          "{iwnAmzqxMkh@~@eq@cCuPoEi[eKgF{@cMmAcK}CiQaFic@kIwHwCkgAck@wFiC{_@eOyfAu`@eH_Buh@P{SiA{EcAu_@_PuGkD}MmIw[sTiSeOeDqBqe@eQiQkG_I{F_f@e[gLmH}B{@q]gUmCkB}ByBcJgMiAy@qA_B}@kDqBeEcJ}NmF{HgDyFyBeCeDqBnBcAJSEUaFcJqBuCcHwNuFgIiw@au@q`@o`@sh@qf@ynAulA}Xo_@oEsE_EiCwEeBaY_FgQcCwEsAoDeBoCkBkDsDiBsC{G{M{CaEyDqDmc@}WgEuBaHmBFQ|BH`@e@nAmUr@cH^uBnDuLjDgH~FgHrGeFxHwDdEoAdFcAbw@sJpGKhGdArE|BvKjJ`BdAzDrAjFb@|CGhn@uDlJqBvIcEpDsChDyDrRyVjEoH~AwE~@qEdHcg@~@}CfBkDrD{DdE_CnQgEfI}CdGuDbFuEbG}IlDoIjAsF|@cHtCgGhEmOvDqHhW}\\tFkKnBqCtNoLzMwMnDaClCqAhGqB~jBwc@hQiF`HgCbqEyjB`GuCvw@}d@xLgF|NuE|QmDnyBuZ|Gi@fn@{Bp_@_C`K[dAc@f@iAGiAo@y@sAc@iFm@qAb@c@`Ab@vLv@~Dh@bBj@x@x@\\~@?nAaAzBoGC{A_A_A{DEc_@bAsu@zCyJz@czBxZcThEqMpEsJhEqo@``@cLtFiZ`MuPvH_bDprAaV`IupA~Zyb@tKmFjBgHjE{LzLaOzLkAzAyGbLeXn^}BjEaBjEkCfJaCvLoAtCaDxK_C`FwDpFgFhFgG~DuIjD{OrDqFxC_EdE{AnCkBlG{Gxd@sC|J_D~FoK~NaIlKgF~EuErCiDvAcInBct@hEaFOcFkAwDqBcI_HwDiCeC}@}Eo@{C@_E\\_q@lIgJhBkJrDyHnF}C`DcCbDoEjIcCxIDl@q@rFcBh[L`@l@h@`CfAta@vVpG`FhFhHlFpK|BrDhCnCbEtCxDbBxD`AjOxB~ZpF`EzAvGbErXd_@`DxDfi@|g@r@dAhCpBpkAthAbb@db@zr@hp@hCzD`HhMvBrAlCjEpO~YnRn\\rAlBzC|ChAvDjHfNp@x@`EhDjaBrfA~NfFhh@rRjKjH`JbHlIlF`RrM~NfJrNzGhUnJ~F`BrOdAvKNp`@SlCZvEnAfmAzc@jZrL~lApn@tEjBlDbAx_@~GnTnGdCf@jQdCbBMxB^nf@fOrOnDvb@dBjKJxLk@|PUfEOb@Wd@HzJ_@p`@e@pMAXJBT{@XgOMcMZwIA",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.07, 77.59],
      average_speed: 9.528,
      max_speed: 15.06,
      average_cadence: 92.5,
      average_temp: 26,
      average_watts: 150.7,
      max_watts: 543,
      weighted_average_watts: 164,
      device_watts: true,
      kilojoules: 1719.1,
      has_heartrate: true,
      average_heartrate: 162.3,
      max_heartrate: 189,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 932.8,
      elev_low: 867.9,
      upload_id: 15043127460,
      upload_id_str: "15043127460",
      external_id: "garmin_ping_426336198597",
      from_accepted_tag: false,
      pr_count: 11,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 101910,
      moving_time: 13190,
      elapsed_time: 13271,
      total_elevation_gain: 612.2,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14074399653,
      start_date: "2025-04-04T00:34:52Z",
      start_date_local: "2025-04-04T06:04:52Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 0,
      kudos_count: 99,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14074399653",
        summary_polyline:
          "yjwnAizqxMcPVuJ\\uJJah@kBaCSsBA{EeAmLeDgUuH{DeAmDo@eMgAgHiBg@]cTeGy[_GwEeAqC{@_DsA_ZcOwl@g[sFeCiLyEgn@qUwk@ySqDaAqCYsa@ZmHKyPiAqB]mBo@o_@}OiFoCgNqIaSoNeHoEgImG{G}EeDsBeBy@{WuJwMyEcIgCuCoAeWcQm^wUmFcDmAYw^cVgDcCK?iCwC{EgH}C_D_BwBYmB_A}BkAsBgCmDcFyIeEiGwE{HiAqA_Aw@{BgAAMjB{@LUAKiFqJgBeCcCoFyDkHkF{HiHsGcEeEic@qa@cRkRiQ_Qo^e]kJqI_M}Lo^u]a^y\\cEuEqToZaEeEaBwAmBiA_CcA_DaAaK}AqKqByQmCuDeAcDyAwDiCkCoCeC{D_GuLkDuEaD}C}AkA}^sTs@k@qIeD_Do@qFw@_gAiMeV_Diu@}H}OsCeE]qk@EmVTef@MsJFcmAMy~BAwFAmWc@_h@HkgAg@}b@c@{DRmNUyBOcBUgHkCoC{B{BiCwBkDq@qBcc@is@mC_EyC_DkE{CqDcBgBm@_GkAkHg@kOs@mJWmL{@i^aByfA{FaGQyELgFp@qDx@g_@hLezA|b@mCf@iEVkEMyDo@yb@wLmAi@uF}Ae@c@w@_@{KiDs@QM@`@X|}@~VrDn@vENlDUfDq@nfBwg@pSsGrE_A`Ea@vEKvDJzhBfJlJr@~KZrQ|@vGn@nCh@~Br@zFnClEhD`BfBfB`Cxi@h}@bArAdC`CxAb@rErB~Ez@~CHfE\\pe@h@frAp@bUM|PDrX^roCBv`@Jzk@Evf@JvWUlh@HfEP`KlBbHbA|t@~Ht_A~K~`@bFxFdAfFrBlDjBl]xSlCtBhAbAzEzGzFbL~AjCdBtBhAdAdD|BdD|AjEjAnS|C`WpErBn@dCjAjGrEnBzBbSrXzDzEpmAlkA|g@ze@pQdQhTrT|W|VpY|WzCdEpH~M~@b@nAlAjB`DxA~CfSz^dNpU`EpEd@rBd@jA`HxMl@t@tDvC`lAvv@tTdOzB`AhGlB~StHjSrHvB`A`LvH|HhGnIlFdR|MrNzI`JnEf\\dNlCv@`BTdP`AlIJv_@YtCTlEhAnHdCbnAnd@bSfIfkApm@pDzAhErA`\\zFxFlAhOvEbCj@dRlCvC?fBX|EpAfThHvJtC|IlB|@^r@Jjj@xBx_@aAvG?LKnBSjGW~\\e@xHG|ENdBER@p@d@mRA{M^}EIeFBwI^QCIMJe@RK|EW`GGLU",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.726,
      max_speed: 15.42,
      average_cadence: 76.3,
      average_temp: 24,
      average_watts: 88.2,
      max_watts: 421,
      weighted_average_watts: 110,
      device_watts: true,
      kilojoules: 1159.3,
      has_heartrate: true,
      average_heartrate: 114.6,
      max_heartrate: 173,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.2,
      elev_low: 883.7,
      upload_id: 15023627546,
      upload_id_str: "15023627546",
      external_id: "garmin_ping_425711720044",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 101917,
      moving_time: 13255,
      elapsed_time: 13309,
      total_elevation_gain: 608.3,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14064797530,
      start_date: "2025-04-03T00:34:12Z",
      start_date_local: "2025-04-03T06:04:12Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 0,
      kudos_count: 101,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14064797530",
        summary_polyline:
          "qjwnAgzqxMoFNuDGsI`@cNTaEAyFMiWsAuK_@sDw@wNaEkX}IoE{@kJ{@qEu@kBa@wAc@w@e@cNaEaEcAk\\_GeEcAaHkCq\\yPyFaDy`@sSqFeCaVqJqpAoe@sF}AgCWmc@XqCCoSkAsB]oBk@e^eOyH}DwMgIaSsNuHyEqH_GcMqI}BcAm`@uN{NyE_CeAgNuJch@q\\yEyCs@KiAo@g\\iT_EsCwAsAmAsAcGsIwBuByAqBo@wCaBaDqE_HyEkIiEkGqCyEkB}BoDuB?MfB}@L]kFuJiBgCwCoGiEiIcEsFsI_IoDqDce@kc@qR_Sek@si@_M_LqSiScx@iv@gDyDaVe\\oCkCgEyCiFqBcCi@iHeAaKoBmQgC}Cu@uEkBwDiCkDoD_CqD_FaKsA}BmBaCiDcDuB{Aa`@kUoA]{BaA}ASqAo@sAYiAc@w`B}Rqu@aIsHeAeI_B}E]cj@EgXTme@MqLFug@Asb@QiSH_lBEq]e@eh@HecAg@ah@c@yCPaPYiDi@yBk@kBs@mBmAeD_DgDcFi@gB{d@{u@}B_D}B}BaEsCmGoCkGqAaIk@qNo@iJWsJu@u`@iByhAcGyEEmENmEf@kEbAwa@hM}vAra@_Er@gDPqEQqDo@e\\eJiOqEmA{@sAg@oKcDODZTrDfAjy@fUhDf@|DLvDYpDs@z}Amd@rYaJxEgAxFo@bDKfEBxlBvJzHj@vKZzPx@rGn@bGvA~EzBxCnBtAlAvBzBxArBtd@xu@`FzHlAtApAhAbANrEtBfDn@bNr@z^`@vsAt@|XKxSDvU\\`bCB|fAJ`SE`e@J~YSvg@F`F\\zIbB`IfAtk@dGtdBlSdDt@bCRdCj@zEjB|BjAl^lTnCpBnAhAnDnE~HlOlBxClDnDpD~BjCjAbEhAnRrCxGrAzN`CtBn@|Ar@lGzDlC|CbVj\\~BjCfnA~kAdUfTdR`QvSjS~MlNjTpSp_@t]hB`CfAhBjGdLpBxA~@bAdCvEj@rApHtMtCtFnQf[vB`D`DfDXbBVx@nEtIlB~C|BhCroAjy@bTxNfCfA`GfBvJjDr_@nNpNtJ|GpFhF`DzUnPxMfInIdEf\\dNjBj@`BZxQhAvHHj_@WfBF|ARpDbA`InCr_@vN~G~Bze@lQvOpGdFbCdeA~i@nD|AzEvAp_@|GrCr@~NrErCn@|RnCv@YtCd@xF~AjX|ItIbCtIjBxb@hBtHRfAQl@RfAOhH]jVa@lBSd@MfKYjd@a@vHDXl@aSEwK\\}BIcIF}J^QGEQBg@LE~M[TG",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.689,
      max_speed: 13.52,
      average_cadence: 79.6,
      average_temp: 25,
      average_watts: 90.5,
      max_watts: 432,
      weighted_average_watts: 111,
      device_watts: true,
      kilojoules: 1196.1,
      has_heartrate: true,
      average_heartrate: 122.4,
      max_heartrate: 167,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.1,
      elev_low: 883.7,
      upload_id: 15013528656,
      upload_id_str: "15013528656",
      external_id: "garmin_ping_425400480301",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi ⛰️ x 2 - PR 😮‍💨",
      distance: 112194,
      moving_time: 14640,
      elapsed_time: 14675,
      total_elevation_gain: 1382.8,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14044896534,
      start_date: "2025-04-01T00:38:25Z",
      start_date_local: "2025-04-01T06:08:25Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 23,
      kudos_count: 114,
      comment_count: 5,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14044896534",
        summary_polyline:
          "kgwnAs}qxM{d@zCiOIef@oB_n@wQwToCm]_Kqb@eIcHiCyoAyo@igBup@}HeB}k@L{PiAaFkAof@iTidA}r@yw@qYk_BedA_ImGgOsRmBiG_Y_d@kGwExBiBwRo^_GwIeoEshE__@ye@_F}D_I{C{k@qJ_JkD}HcHyJcRqHwI_d@oXiNiE}DzAcfCf|Au|@nScb@vMwiCth@{aCpa@dF|OhBzt@oDl[qDrSkHri@qVhp@yR{GgB_GqDTe@_@a@oFLsE}AoFVwJ]gPq@}PwA}J_GsLEeG}@}Cn@wD@{JsD}QiEkMcBoQaAk@w@h@YnEmD`CUj@WnJyEfD}@|AwBl@mBfGkBjBKtE}B|C_@M~@qCAeCgBpAcFs@iCyCnEV`Da@_MyCdN_BaC}@yDPdEuBtBKoLQ?]jCUsBs@pBr@mCj@xHGtBXkBPiEnBjDMhC|@_N`B`MvCcDh@uDm@UXtBbC`F~@pBuALzBcA|CVP~ByCHsEhBiBrBmG~Bo@t@{AvEkD`@}JfBq@rAaBVcFbAg@`Ar@`BnQfEnMrDlRAlIs@xDbAtDCvFdGvLtAlJr@zPZ~QWlIzApFF`Ml@j@rDUjBzFnEdArKdFkK}EoEeAmB_GyECa@}FJoEyAiFVaJqAmc@uAmJiGwL@cG}@mCr@qF?oI}@aCsByM_B_DgBiHeBoQiAo@w@j@UhEkA`BuB`AYtJyElDy@zAwBj@mBfGoBlBGpEcC~C]E`A_DC}ByBrAiF}@oBkC^WpIJcM}C`N{AyB{@{DJlEyBjBI{L_@xCa@sBo@nBj@qCl@nDXhD[|Ab@}AA}EvBnDOfCbA_NtA~LzC_Dj@mEYpBhChDRr@h@~BqAEjEu@xAb@EvBsCHoEhBgBvByGhB]dAiBnEuCd@iKtDmC^kFx@i@hAn@bBvQbBxG~A~CxB`Nz@xBBpIw@~FdAlC?nGzFvKzAhKn@pP`@`QYfJ|AtFMnE^zF~EHfBzFrR|GbVuo@rFeb@~E_Y~Do]_B}s@iF{OAy@l}Bm`@r}B{d@hR_E~`@gMvz@yR|iCy~ApAk@bCRlKbEtb@pWxExE|NjWrIfHpHlCrk@jJ|MpGz^xe@|vBtrBte@ve@zr@bp@pMlTjChBh]rn@~JxPxDdEhAbElGrLtDxDzbBxgApx@~Ypu@vh@rP~Jri@tT~TtAdg@QvFr@tnB~s@nrAhq@be@bJ~XxHpXvC~s@`Txl@~Btw@{Bbi@Y",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.664,
      max_speed: 16.74,
      average_cadence: 83.7,
      average_temp: 22,
      average_watts: 127.8,
      max_watts: 626,
      weighted_average_watts: 169,
      device_watts: true,
      kilojoules: 1869.4,
      has_heartrate: true,
      average_heartrate: 151.1,
      max_heartrate: 200,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 1366.7,
      elev_low: 883.7,
      upload_id: 14992433116,
      upload_id_str: "14992433116",
      external_id: "garmin_ping_424767563701",
      from_accepted_tag: false,
      pr_count: 21,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 106875,
      moving_time: 13812,
      elapsed_time: 13855,
      total_elevation_gain: 629.4,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14025623175,
      start_date: "2025-03-30T00:22:34Z",
      start_date_local: "2025-03-30T05:52:34Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 0,
      kudos_count: 116,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14025623175",
        summary_polyline:
          "{iwnAezqxM_OPoRr@uE?{o@iCsUsGwVeI_Ew@_NoAe\\qJge@cJsIgDqbAih@cKyEkz@u[qm@qTiCq@yCWya@XcGIwPeAmFkA{]aOgIeEqLmHkTqO{GgEsRwNcDmB{h@yRuIoCyCuAwIiGob@uXeNyIoCiAy\\wTkDaCcC}BaGgIeGeHSoB_CeF}CgEuRe[oCqCyBmA?[fBk@LSAWgJuOmH_OqF}Hoe@oc@kt@ys@cg@ce@amA_kA}CqDsTqZmBsB{FmEuGcCuVkEsS_D}Cy@gDyAiDyB_D{CwB_DwIsPyBoCuCqCwd@_YwE}BcFoAFQrBARc@nAmUdAmJfCiJ~AsE~@kBpBaDtCkD~CwCfDcCnHqDlFcBxE}@dt@_JnD[bC?pBJ~Cl@|EtBbLxJrBnAxDpA|E`@bb@qB|PoA|E{@rDgApCmAbEaCzFqFrRuVdFaIhBgFbAkEvHsh@`AaDrAcCpCgD~EaDbCw@rN}C~H_DnFgDxFkFrFmInDuIjAeFr@uFZoA`AgBjAaDhBqHfAcD~DcInXu^rE}IrBuCpOiMnLoLpDcC`D_BfIeCt{@yS~m@yNhYgJjpEqjBrHsD`u@ec@lLgFrPqFbQcDzyByZrHm@tm@wB|_@_CnISzA]t@aAAwAu@aA_HsAkBd@e@rARvHl@jF`BlE|@j@r@B|@Ub@c@zBkGDuAUk@i@_@wBO_c@nA{L`@{d@pBkMdA}rBfYsLjBcLdC_NrEeJdEco@r_@qNdHyR`Iw_@pPqzCtnAuS`HytBtg@}GdCgGzDkMhMuNrLiElHcCtD}RlWuDrFsDvHgB|FcBlGeB|KuAdCuBzGmB|EcB|CkDxE{ErEkG~D}IjDsOpDmE~BqBbB_BlBmBtDyAhF}G~d@aAfEwA`EyBfEiMlQeHdJoElEgEnCeCjAsEzAqE|@{s@dE}DMmE{@{EaC_IwGsDgCgEwAcEc@sELof@bGgPtB_GnAcJnDgH~EgCdCuCpDsFbKwBxH?bAm@nEgBj\\LXfAt@|B`ApAdAb^bT|GhF|DxEb@nAxIbPhDvDjDbCvDdBnD`AnSzCpVlElFjBpGzDdY~_@jC|CloAfmAvi@pg@rm@jm@xg@le@rCxDtHdNnBrA|@dAp[dl@rKzQjE|ELfAf@~AnD|G~B`DfBbB^|@deBtiAtUbIz_@rNtNrJnf@n]bMvHdJrE|ZpMvFxAhSjAli@MvC^jFxA|uA`h@lR`IfjAzl@nJpDda@pHdV`HhTzC`ASpDn@ha@hMdRvEnd@nBbJJdBe@|AIzVi@xJi@dNYPIBe@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.738,
      max_speed: 11.84,
      average_cadence: 79.2,
      average_temp: 24,
      average_watts: 96.1,
      max_watts: 405,
      weighted_average_watts: 114,
      device_watts: true,
      kilojoules: 1327.1,
      has_heartrate: true,
      average_heartrate: 120.1,
      max_heartrate: 153,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 932.8,
      elev_low: 867.9,
      upload_id: 14971734777,
      upload_id_str: "14971734777",
      external_id: "garmin_ping_424055907880",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 101912,
      moving_time: 12451,
      elapsed_time: 12498,
      total_elevation_gain: 608.7,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 14007996609,
      start_date: "2025-03-28T00:36:56Z",
      start_date_local: "2025-03-28T06:06:56Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 1,
      kudos_count: 101,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a14007996609",
        summary_polyline:
          "qjwnAizqxM}GFqNd@kNNcIQ{^}A_D@qF}@qJmCq^gLqF}@cJu@mIqBaAg@qS}F{`@oHoDeAsD}AcUgLum@w[yJuEcKgEma@mOas@qWcF_B{C{@wCYqa@ZqGIiQiA}AUeCu@o_@}OkGeDaMyHaU_PyFoDaHoFaJsGqC_Bae@_Q}LaEmCiAsKqHkj@o^uEqC}B{@qRqMePqKyBaCuDoFuEkFyAoBW_BW{@qBgEwBmCqG{KcFqHsC}Eo@y@{AuAeCsAASbBk@PQDWsFyJmBoCiCwFaDkGkDgFcByBeGmF{F_GgHkGe[gZ_TgTiP{OmZgYwH_HmTeTkz@ox@gDaEmTkZyA_BkDsC}A_AuCoAsBm@uYeF_OuBeFqA_EkBgDaCoCwCmCgEqDeH_BgDqBmC}DwDcEqCq]uS}DwAqB_@kFkBk`ByR{y@_JiM}BeC]qBM}j@E_XTw_@Mio@Bwl@KqdC?u`@g@s^L_dAi@sk@e@iCRiMUoFa@eEqAkBaAwBaBcCoCkC}Dc@}Aed@yt@iCsDiCmCwAiAoCaBgCkAoC}@yEaAaMw@iV}@kL{@ed@uBacAmFoEIkDHqFl@kFlAuXtIo_B`e@}Dp@iDNeEOiEu@c^{JoAk@oJkCuAeAsLqDk@MKF`Cz@f{@~UvCj@zENfDSxDq@lbBgf@rV{HbFgArD_@vDMpED~lBtJbIl@fJVdTdArFp@`FnApFhCxBzArBhBnDlEtg@bz@~CtE~BzBtAT\\Z~CrArE|@hENdDXxf@h@hrAr@hUMfSDbY^pjCB~oADdh@HtUSzh@HxE\\`KjBtFv@lWjCtq@xHdhAzM|Cb@tDr@bDdA|Ax@XAj\\|RbInFtAlAnCdDp@`BjA|ArEjJxBdDtDrDtClBbDvApDbA|QpCtIbBtMtB`FhBdGpDbCrC~T|ZdDzDhnAdlAbKfJn^f]fNzMvPdQdH|Gz^~\\rL`LxCfEnGnLh@n@xB`BdC~DxEjJnH`NvFzJ|LvS`EnEf@xBdBtDrDhGnAbBjAhA\\v@hE|Cx\\vTzi@v]zM`JfFnDzBbAdKdDxPfGzU`J~GnExNvKpHvEbRzMrNzItIhEx[~M`Cv@|AVnD\\vJh@jCHpJDf[YzD\\`EhAvLbEfq@`W`XrJlHvCxNtG|LvGnv@x`@xDbB|FdBbStDbIpAlY`I|QfCd@@p@QdEt@|EtArS~GhMrDdGjAr@ZnANd`@dBfKP|ZgAjIErAI\\Mj@BxKg@tE@~NYfMJzHERJ]VYBeSIuJXqNF}IVMa@JYxAK~JU",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 8.185,
      max_speed: 14.3,
      average_cadence: 80.6,
      average_temp: 25,
      average_watts: 110.6,
      max_watts: 471,
      weighted_average_watts: 135,
      device_watts: true,
      kilojoules: 1372.9,
      has_heartrate: true,
      average_heartrate: 130.9,
      max_heartrate: 184,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.1,
      elev_low: 883.7,
      upload_id: 14952689445,
      upload_id_str: "14952689445",
      external_id: "garmin_ping_423385516454",
      from_accepted_tag: false,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Nandi ⛰️",
      distance: 101276,
      moving_time: 13402,
      elapsed_time: 13420,
      total_elevation_gain: 1000.7,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 13998713758,
      start_date: "2025-03-27T00:33:21Z",
      start_date_local: "2025-03-27T06:03:21Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 7,
      kudos_count: 111,
      comment_count: 3,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a13998713758",
        summary_polyline:
          "kjwnAczqxM}f@z@sq@iCkQsEg\\kK}R{Ba^iKqc@mIsHwCylAcn@o}@k]gn@yTuGy@ii@PkQkAuEgAs_@aPkHyDmi@e^{WkRyv@}Xqv@sg@oO{Ia^}UuBmBmIkL_EkE[kBmCsFaWga@_BeBkDyBpBiABa@{I_OeHyN}GsJow@{t@m_@o_@cuB_qByEkFaUe[aD_DeE{CuGcC}j@eJ{IaDeDyBwDyDeL}SyHiImd@qXiLcDs@@mFzCccChzAq{@bSya@tM{pCtj@{{Bx_@Gp@fEdK`@fCjBvp@O|CoD`[mE|ViGde@yTrm@y@pAs@IoJsEmE}@e@q@_AmEuDLk@]]_GN}D}AqFXgJo@qLL_Ck@sP}AqK}FqLEeGu@aBIcAr@wE?sIaAwCOkCcB}HyAwCUuBuAuDi@kJy@eFgAk@s@d@]tEwAfBwAZQh@[jJyElD_AzAmBf@oBhGkBjBMrE_C|C]Eb@k@X{A@uCiBpAgAg@cCI_A_@{A{BRQxDh@rCOHQ_IeC}BUxEa@zBu@lCEaC{@yDN`EuBvBMyBYkC\\sDg@vCa@uBs@zBj@uC\\@XhDRtC[vB`@iBBwEvBrDSfCh@G\\cCBwBp@cF`@jCT|HdCyCd@cEm@YNfB`Cz@\\`C@fAf@fBoAHnBSfBs@fAXHbC_DGcCNuA`BqApBoGj@e@rAM~@iBjEqCRo@R{IVc@vASrAeBCiCZyAr@a@dAf@fAfGd@|IrAlDX`CpAbC|AbH^xD|@xCA|Hw@jF~@rCBfGpCrGjBvC|AjKJxHb@zFMxCj@fKWnJzAdGKfE\\zFd@X|DMt@zDn@dAzDv@|IfEtAVhV}o@xGag@|EoY|CkXDwBiByo@e@sCmEoKLo@ryBg_@dhCah@zKaCl`@aMb{@_SxjCq_BlD@`JhDfd@pX`GjGnMrUtCzCdD|BrJfD`k@jJtE`BdFrDh@Bp^|e@zcAbbApq@~n@lc@nc@fu@pr@rCxDpHbNzBzAvCrE~NzXjS`^pFrGXjBx@fBfIlNdG|Eh_BbeAfw@fYvVnQn\\fUhOhJ`g@pTnEdA|RhAvi@KpIdBbzAzi@hL|EpnAfo@hI~C~d@zInTjG~RlCpAOzCj@~b@~MzPbE``@dBjNL`]gAnEBjLu@pb@g@lON_AZgRCkf@|@SOpGi@zU]l\\HkB`@{QQm]f@kF^UURq@pNm@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 7.557,
      max_speed: 14.5,
      average_cadence: 80.3,
      average_temp: 24,
      average_watts: 112.1,
      max_watts: 423,
      weighted_average_watts: 146,
      device_watts: true,
      kilojoules: 1498,
      has_heartrate: true,
      average_heartrate: 144.6,
      max_heartrate: 189,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 1366.3,
      elev_low: 883.7,
      upload_id: 14942729704,
      upload_id_str: "14942729704",
      external_id: "garmin_ping_423085854812",
      from_accepted_tag: false,
      pr_count: 5,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Morning Ride",
      distance: 101779,
      moving_time: 12778,
      elapsed_time: 12820,
      total_elevation_gain: 608.2,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 13978921187,
      start_date: "2025-03-25T00:36:56Z",
      start_date_local: "2025-03-25T06:06:56Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 0,
      kudos_count: 101,
      comment_count: 2,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a13978921187",
        summary_polyline:
          "akwnAkzqxMoZr@qJJ{HOch@uBwBa@mQeFyKwDqKaDqEs@{Iw@sDq@oDaAcAg@cSyFs\\eGqDy@cEsAcEiBuZsOyi@mYyHkDaKaEek@aT{g@gR}GyBgCi@aCOy_@ZsGG}QiAwB]}Ac@uY{LcCkAy@UuFwCoNuIuS_OiIkFgFeEwIiGiDuBo[uLuW{IqB_AyKuHih@}\\eGwDeCaAyTaOmMgIk@{@cCmCoCaEqEcFeB_CScBaBoD_FsHmEyHqDeFcEeHeCmCiCwA@S~Am@NQBWsF{J}AsBeBaEaE{HmFaIuB{B_DmCoFoFkh@of@kNwNiO_Og_@_^yI_IqmAmkAuCgDqTmZsB}BoBgB{AiAeB_AoEaBcNaCaHsA}S_D_FyAoB_A}DkCiDqDqBeDmHsNiDcEkDyC_b@{VuEeB{ASsEeBovAuP}HiAgw@gIqSkDmEUeg@EcXTug@KmIFkd@Cag@MceC?_d@i@c_@LcpAm@yZ]wCRcLOqCSeCYkEmAiBcAsC_C{AaBqCgEa@sAyAgCab@yq@mAgBwBiCsEmD_FcC_FyAoH}@qS_AiK[qJu@cYqAgpAyGuDEwCH}Ef@sE`Aa\\~Jm~Ard@wAXcF\\{EKoDo@g_@kKuAk@eJgCuBoA}J}C_AUMFlFbBjx@xT`Fr@zCDnDWvCi@`cBof@bVsH`FgAtDa@pDO`EB`jAdGx_@fBzM~@hGL|Qz@hGf@dGpAfFvBxBpA`ClBlBnBtBpC~f@~x@dDbF|@dA|AnA`APtEpBpEr@fENrEZz_@b@tqAt@j[KhQDjW\\hhCBhsAF~d@HlYU`j@HbF\\fLvBxEn@vs@vHf|AzQ|D\\~FtAtGfCdCtAh[jR|DnClDlDrApBnArBxF`LpB|CtDpD`DrBtClA|Cz@lHpA|H`AhXzEzC`AdBx@nAv@nB~AdAd@pCjDxQ~V~EdG|h@rg@rd@vc@xLxK~HzHnOrNhSzR~KjLtJnJzUzT`RrPvCzCxB`DbHjMzA`AxA~AbRt]fRh\\hAhBpCvC~@pARpAn@bB`HjMb@j@jCdCdAt@~p@~b@x`@pWtM`JnAl@vIpC`SdHfVhJ|KpH`KzHdGvDnTtOnM|HbI|Db\\dNfCt@xB\\fRdAzGF|_@WzC\\`FrAhzA`j@|PjHliAnl@jEhBlEnAx]lGzD|@fNfEtCr@lRjCjBKrB\\dHnBhTlHfMlDrEv@fAd@lOv@f]fAt]eAnABzDOr@D~AYtGYfTWhBHnLK|IDvAADGFJS^[DkNMkGD{FLiODyGPcAJQMMw@HmAd@mC",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.07, 77.6],
      average_speed: 7.965,
      max_speed: 13.38,
      average_cadence: 80.1,
      average_temp: 24,
      average_watts: 95.8,
      max_watts: 382,
      weighted_average_watts: 118,
      device_watts: true,
      kilojoules: 1222.2,
      has_heartrate: true,
      average_heartrate: 119.5,
      max_heartrate: 166,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 933.2,
      elev_low: 883.7,
      upload_id: 14921592146,
      upload_id_str: "14921592146",
      external_id: "garmin_ping_422472259256",
      from_accepted_tag: false,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false,
    },
    {
      resource_state: 2,
      athlete: {
        id: 33062021,
        resource_state: 1,
      },
      name: "Non-stop 200K @31.3kmph",
      distance: 202572,
      moving_time: 23297,
      elapsed_time: 23367,
      total_elevation_gain: 1350.4,
      type: "Ride",
      sport_type: "Ride",
      workout_type: 10,
      id: 13960248068,
      start_date: "2025-03-23T00:31:49Z",
      start_date_local: "2025-03-23T06:01:49Z",
      timezone: "(GMT+05:30) Asia/Kolkata",
      utc_offset: 19800,
      location_city: null,
      location_state: null,
      location_country: null,
      achievement_count: 24,
      kudos_count: 147,
      comment_count: 8,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: "a13960248068",
        summary_polyline:
          "qiwnAkzqxMef@hA}o@qBcq@sRaUwC}[kJuc@oIozA}t@wjB_r@uEe@yi@PkQkAwEgAsf@iTidA_s@{x@eZueBmiA{QaUoCcI{Wkb@iGqEtBsBoY{g@ysEcmEk]kd@oM{Gok@kJyJqDeIgHcL{SeHwHkc@aX{MaFdCq@rCe`@vEcPvDiHvFsGpPeKzMcDzu@gJpGIpGhAfUlPnJlBfu@yD~J{BjIcEtHgHhYs`@lE{PfGec@tDuItJuHh[yIpNsKdFuHpDqIbD_Q`J}W`DoGdXg^rIeOh]a[xJuFjpB}e@lY}IdrEgkBv~@{h@z`@aOvkCu_@|aBuHhBu@NcCgAiA{FaAsB\\k@nATnJ~@jFrAdD~Bd@vAgAvBgGE{AeA_Aa}A`FozBfZs]nGmXjKmo@x_@mPdIgmEfiBeUtH_zBbj@_JhF}\\xZwIpNmWl]wFpLqFrV}F~PqIbOmOxLiYfIwKtH_FlLkHtf@sDlL{Uz\\}J~J{InEiInBkt@dEcMgB{RwNeLiCa{@nJ}PjEuMjIeJnLgGrPy@vFkJncBwK``A_BtYV~NhBjO`Svs@p@tHGbKgTniBmDhd@st@|lDiMtaA}Dno@yOzu@mGnz@vB~Lpa@fqAvKzU|SlX`IxYp@rGxCflA[lN{C|MkKhRmCjHyAjIiE`j@_DtKoEnHaN|KgmBz|@_ItIkEtJwBpLOpK`o@thH|OlvB`aAh}HvIfm@@~Vb@vEbo@~|ClEpOvA`LvMno@rE`P~nAreCntAtmBzCdHrAfM}Cx[l@|Q|h@vrCjUlrAfHjh@KlAy@h@go@bMoHtDmTx]s^dc@kOp\\wKlKyU|]y^lc@{m@tj@eH`JiEhM{BbDuQzKkNrLtK}KtTkN|GeQjIkKtm@ij@|\\oa@tVa_@pK{JtPo^d^kb@bUo^|FoC~r@uNnHmD`b@ya@pKqPtTqU~gEuhEnc@aw@jJaXpYwm@tiByuCnKcWvBiM|A_E~C}CzRqKpIuHrq@{aAz[iWlhBscBjEaGlF}CdKwJnJiFnd@mOrIkEnd@u_@hHwLlV{_AtB{Ch]yeAh_@qdAxSc{@fcAa|Bvg@cdAhYy|A`x@m}CzF{XbHaQbIc\\rKyNlXem@dG{Yp`@a{@_z@sLyMaQyRuz@lAcVAoOy@aDgMuSoAkEcBcZcBqp@rAoG`MyPjIaQtBiQwA_K{BaAqIm@cUyImVsDwn@R{h@|@j@g@`IWfp@Us{@jAZu@nN{@",
        resource_state: 2,
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: "everyone",
      flagged: false,
      gear_id: "b12263177",
      start_latlng: [13.07, 77.59],
      end_latlng: [13.06, 77.59],
      average_speed: 8.695,
      max_speed: 15.54,
      average_cadence: 86.2,
      average_temp: 27,
      average_watts: 128.5,
      max_watts: 611,
      weighted_average_watts: 148,
      device_watts: true,
      kilojoules: 2958,
      has_heartrate: true,
      average_heartrate: 154.1,
      max_heartrate: 185,
      heartrate_opt_out: true,
      display_hide_heartrate_option: true,
      elev_high: 946.4,
      elev_low: 842.9,
      upload_id: 14901584186,
      upload_id_str: "14901584186",
      external_id: "garmin_ping_421890136733",
      from_accepted_tag: false,
      pr_count: 13,
      total_photo_count: 0,
      has_kudoed: false,
    },
  ]),
  transcript:
    "Hi Ajinkya! How can I help you today?\nHi, please help me transform my Himalayan race in August.\nThat sounds like an exciting goal! To help you prepare effectively for your Himalayan race in August, could you tell me a bit about your current fitness level and cycling experience? Also, what kind of training have you been doing recently, and what are your specific goals for the race?\n\nThanks, Mai.\n...\nYeah, I need to prepare for it. I'm very serious about it. So bye.\nOkay, good luck with your race!",
});

console.log(JSON.stringify(result, null, 2));

import fs from "fs";

fs.writeFileSync("result.json", JSON.stringify(result, null, 2));
